export const locURL = "https://wft-geo-db.p.rapidapi.com/v1/geo/cities?";

export const locOption = {
  method: "GET",
  url: "https://wft-geo-db.p.rapidapi.com/v1/geo/cities",
  headers: {
    "X-RapidAPI-Key": "8fa6b215a7msh4b4e9b9715d9f45p154949jsn35d105890ba7",
    "X-RapidAPI-Host": "wft-geo-db.p.rapidapi.com",
  },
};

export const WeatherURL = "https://api.openweathermap.org/data/2.5/weather?";
export const ForecastURL = "https://api.openweathermap.org/data/2.5/forecast?";
export const WeatherAPIKey = "31fafe69dbbdcdbbcd74baa155007804";

export const WeatherData = {
  "Ashvolcanic ash": "50",
  "Clearclear sky": "01",
  "Cloudsbroken clouds: 51-84%": "04",
  "Cloudsfew clouds: 11-25%": "02",
  "Cloudsovercast clouds: 85-100%": "04",
  "Cloudsscattered clouds: 25-50%": "03",
  Drizzledrizzle: "09",
  "Drizzledrizzle rain": "09",
  "Drizzleheavy intensity drizzle": "09",
  "Drizzleheavy intensity drizzle rain": "09",
  "Drizzleheavy shower rain and drizzle": "09",
  "Drizzlelight intensity drizzle": "09",
  "Drizzlelight intensity drizzle rain": "09",
  "Drizzleshower drizzle": "09",
  "Drizzleshower rain and drizzle": "09",
  Dustdust: "50",
  "Dustsand/ dust whirls": "50",
  Fogfog: "50",
  HazeHaze: "50",
  Mistmist: "50",
  "Rainextreme rain": "10",
  "Rainfreezing rain": "13",
  "Rainheavy intensity rain": "10",
  "Rainheavy intensity shower rain": "09",
  "Rainlight intensity shower rain": "09",
  "Rainlight rain": "10",
  "Rainmoderate rain": "10",
  "Rainragged shower rain": "09",
  "Rainshower rain": "09",
  "Rainvery heavy rain": "10",
  Sandsand: "50",
  SmokeSmoke: "50",
  "SnowHeavy shower snow": "13",
  "SnowHeavy snow": "13",
  "SnowLight rain and snow": "13",
  "SnowLight shower sleet": "13",
  "SnowLight shower snow": "13",
  "SnowRain and snow": "13",
  "SnowShower sleet": "13",
  "SnowShower snow": "13",
  SnowSleet: "13",
  SnowSnow: "13",
  "Snowlight snow": "13",
  Squallsqualls: "50",
  "Thunderstormheavy thunderstorm": "11",
  "Thunderstormlight thunderstorm": "11",
  "Thunderstormragged thunderstorm": "11",
  Thunderstormthunderstorm: "11",
  "Thunderstormthunderstorm with drizzle": "11",
  "Thunderstormthunderstorm with heavy drizzle": "11",
  "Thunderstormthunderstorm with heavy rain": "11",
  "Thunderstormthunderstorm with light drizzle": "11",
  "Thunderstormthunderstorm with light rain": "11",
  "Thunderstormthunderstorm with rain": "11",
  Tornadotornado: "50",
};
